# node block
FROM node:20-alpine as react

USER node

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm install     

COPY --chown=node:node . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]


# nginx block
# FROM nginx:1.25.4-alpine as nginx

# WORKDIR /usr/share/nginx/html

# RUN rm -rf ./*

# COPY --from=react /app/dist .

# ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
