version: "3.8"

services:
  web:
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social-frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social-backend
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

volumes:
  frontend_node_modules:
  backend_node_modules:
