services:
  nginx:
    depends_on:
      - client
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: social-nginx
    restart: always
    ports:
      - 3050:80

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: social-client
    volumes:
      - ./client:/app
      - /app/node_modules
    # ports:
    # - 3000:3000
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: social-server
    volumes:
      - ./server:/app
      - /app/node_modules
    # ports:
    # - 8000:8000
    env_file:
      - ./server/.env
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
