services:
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: social-client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:8080

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: social-api
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
