FROM --platform=linux/amd64 node:20-alpine3.19

USER node

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm install --omit=dev

COPY --chown=node:node . .

EXPOSE 8000

CMD ["npm", "run", "start"]
