FROM --platform=$BUILDPLATFORM node:20-alpine3.17

USER node

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

EXPOSE 8000

CMD ["npm", "run", "start"]
