# Stage 1: Build the application with local platform
FROM --platform=$BUILDPLATFORM node:20-alpine3.19 as build
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Stage 2: Create the final image with the platform of the worker nodes
FROM --platform=$TARGETPLATFORM node:20-alpine3.19

WORKDIR /app

COPY --from=build /app /app

EXPOSE 3000

CMD ["npm", "run", "start"]
